### ISSUE TITLE
Not working with swift-numerics

### ISSUE THREAD

**Issue by damuellen** [philipturner/swift-colab#7]
After some experiments I found a bug. It seems to be because I use swift-numerics in the function.
https://colab.research.google.com/drive/1TL70U_I_2wEIyzSa5quB55h54A79bDtp?usp=sharing

**Comment by philipturner** [comment]
Did you explicitly import the Swift Numerics library? If you didn’t, it would crash because of an undefined symbol. I’ll thoroughly examine the failure in a bit.

**Comment by philipturner** [comment]
Also, if you’re running system commands, prepend then with %system and not “!” (when in Swift mode). Also, remove “sudo” from the command because Colab doesn’t allow that or need it. If you’re expecting to use GNUPlot in Swift (I didn’t fully examine your code), you need to import a Swift package that wraps it.

**Comment by damuellen** [comment]
It will probably be due to this function.
https://github.com/damuellen/Utilities/blob/main/Sources/Helpers/ODE.swift
My other notebook does not cause any problems.
https://colab.research.google.com/drive/1vDt4cN1d-zEmdsYgZB7t4QGLehFKBlyX?usp=sharing

**Comment by philipturner** [comment]
Nice example of plots! I was asking the creator of SwiftPlot to provide a Colab notebook to test the IPython display connection's integrity, but I think you've done that!

I worked with Runge-Kutta before for [multipendulum](https://github.com/philipturner/multipendulum), which I saw in the Utilities code you linked.

**Comment by philipturner** [comment]
Also, the %system command can't be in the same cell as a "!" command. %system runs in Swift mode; "!" runs in Python mode. What you have right now should cause a compiler failure in both modes.

If you do include %system commands, you can put them in any Swift cell and they will execute when you run that cell.

**Comment by damuellen** [comment]
> Also, the %system command can't be in the same cell as a "!" command. %system runs in Swift mode; "!" runs in Python mode. What you have right now should cause a compiler failure in both modes.

I'm not sure what you're trying to tell me, but I'm using a modified version of your script in my other notebooks.
https://gist.github.com/damuellen/31ce73e851831839acd14806e97d5ae7

**Comment by philipturner** [comment]
I'm saying that if you attempt to run the following all in one code cell, you'll experience a syntax error and it will never run:

```
%system apt ... (command)
!curl .. (command)
```

The very first code cell of the notebook you showed me would cause that breakage. Also, the first command in that notebook should pull the script from my repository and not yours.

If you want to install extra stuff, I recommend making a cell of %system commands that executes once you're in Swift mode (instead of during a custom installation script). That makes it more reproducible (no divergence from philipturner/release/latest) and should provide the same capabilities as the shell script, assuming you're familiar with the quirks of system commands in Colab.

**Comment by philipturner** [comment]
In the install script, you're putting everything you downloaded into `/opt/swift`, which isn't a good habit in general. By keeping the commands encapsulated within the Colab notebook instead, it would go to `/content` by default (and it resets the working directory to that at the start of every line). You would then have no chance of accidentally interfering with stuff the Jupyter kernel touches.

My choice to put install commands in the notebook is just a personal preference, and your current solution should be fine as long as you know what you're doing 😄

**Comment by damuellen** [comment]
I adjusted the two notebooks as I understood you.

> In the install script, you're putting everything you downloaded into `/opt/swift`,
to bring up a painful subject... 😊

**Comment by philipturner** [comment]
I had a similar scenario where I wanted to keep utilities I created and use them in future software. I bundled some basic utility code from ARHeadsetKit into [ARHeadsetUtil](https://github.com/philipturner/arheadsetutil) and tried using it with [DL4S](https://github.com/palle-k/dl4s) and [MetalFFT](https://github.com/philipturner/metal-fft).

**Comment by philipturner** [comment]
I just overhauled Swift-Colab and completely rewrote all of its low-level code. There is no sufficient documentation about the changes at this time, but I want to have some insight into how it impacts people in the community who use Swift-Colab. When you read this, there will either be a disclaimer at the top of the README explaining how to use the new features, or a 2.0 release in `Releases`.

I know I could run through your linked notebooks in theory, but it's best that you test it since you're an expert on what's going on there. Do you mind running the notebooks through and reporting if anything goes wrong?

**Comment by philipturner** [comment]
I just overhauled Swift-Colab and completely rewrote all of its low-level code. There is no sufficient documentation about the changes at this time, but I want to have some insight into how it impacts people in the community who use Swift-Colab. When you read this, there will either be a disclaimer at the top of the README explaining how to use the new features, or a 2.0 release in `Releases`.

I know I could run through your linked notebooks in theory, but it's best that you test it since you're an expert on what's going on there. Do you mind running the notebooks through and reporting if anything goes wrong?

**Comment by philipturner** [comment]
You may have had a problem with SwiftPlot in `EnableIPythonDisplay.swift`. I fixed it by adding a conditional import statement. Please incorporate the fix into your branch.
